### ISSUE TITLE
Problem: cannot find how to build under Ubuntu 16.04.3

### ISSUE THREAD

**Issue by ashipunov** [trufanov-nok/scantailor#33]
First, there is no installation instruction to build with Qt5. This text https://github.com/scantailor/scantailor/wiki/Building-from-Source-Code-on-Linux-and-Mac-OS-X does not work anymore.

Second, I installed qt5-default and then (following advices from Web) also libqt5webkit5-dev and then qttools5-dev packages with dependencies, but I still continue to receive error messages. Finally, I found that I need to install qttools5-dev-tools, and now ST started to build.

Please update the installation instruction or at least provide some short notes of how to build with Qt5.

**Comment by trufanov-nok** [comment]
Good Idea.
In a meanwhile this must work for Ubuntu 16-17:
```
sudo apt install cmake gcc g++
sudo apt install qt5-default libtiff5-dev libjpeg-dev libpng-dev libboost-all-dev
sudo apt install git

cd /tmp
git clone https://github.com/trufanov-nok/scantailor.git

mkdir ./scantailor/build
cd ./scantailor/build
cmake ..
make && make test

sudo make install
```
Right now it could be better to just launch the app with `./scantailor` from build folder instead of installing it into system as it doesn't create an app icon in menu and can't be removed automatically. 
There are no `make uninstall` implemented to rollback `make install`. It should be in my TODO.
Also I found out `make package` build target in app's scripts that could used to build .deb packages (after several changes in code). Such packages may be easily installed and uninstalled via `sudo dpkg -i ` and `sudo dpkg -r`. I even managed to build such deb. Unfortunately - no icon in it either.

**Comment by ashipunov** [comment]
OK, thank you.

AS

2017-09-26 4:08 GMT-05:00 Alexander Trufanov <notifications@github.com>:

**Comment by trufanov-nok** [comment]
I've enabled `uninstall` target for `make`, so now you always can remove ST files from your system with `sudo make uninstall`. Of course you need to regenerate makefile once with `cmake ..` from `./build` dir before that.

I think it's a good recommendation to use `./build` (or any other newly created) subfolder for `cmake` execution as `cmake` creates millions of temporary files while building and store them in its current working dir. That make source folders messy and could lead to a filename clash and abort of building process.

**Comment by trufanov-nok** [comment]
Wiki page is updated

**Comment by ashipunov** [comment]
Thank you!

2017-09-27 5:57 GMT-05:00 Alexander Trufanov <notifications@github.com>:
