### ISSUE TITLE
Bug: you cannot change despeckle on mixed mode images when screen is small

### ISSUE THREAD

**Issue by ashipunov** [trufanov-nok/scantailor#36]
This is because the left panel is overcrowded. I hoped that docking will help but no, I cannot rearrange buttons to make despeckling visible :(
Workaround: change mode to black and white (or color) -> change despeckle -> return to mixed.

**Comment by trufanov-nok** [comment]
Confirmed. That's why I want to replace some controls with smaller analogs.
Btw, you still can workaround this if you pop out left docking panel to floating mode and press maximize button of a main window on/off couple of times. Without this docking panel inside, the Main app window will be able to correct its size and fit the screen.

**Comment by ashipunov** [comment]
Yes, I agree. But my problem is different: I cannot access despeckle
buttons which are on the left docking panel...

AS

2017-09-26 4:13 GMT-05:00 Alexander Trufanov <notifications@github.com>:

**Comment by trufanov-nok** [comment]
I have added a scrollable area around these controls. No scroll bars are shown, but you can scroll with mouse wheel. I think this could be a temporary solution.

**Comment by ashipunov** [comment]
OK, thank you. Will check it.

2017-09-27 1:59 GMT-05:00 Alexander Trufanov <notifications@github.com>:

**Comment by ashipunov** [comment]
It works!

Thank you!

===

I am sorry, but beep is not working again...

AS

2017-09-27 9:01 GMT-05:00 Alexey Shipunov <dactylorhiza@gmail.com>:

**Comment by ashipunov** [comment]
It think that you might close this issue.
