### ISSUE TITLE
Bug: "Auto Margins" does not behave as a checkbox

### ISSUE THREAD

**Issue by ashipunov** [trufanov-nok/scantailor#9]
If one click on "Auto Margins", these values on the current pages change irreversibly, the only way to return to previous values is to insert them manually. This is not a check box behavior, and not similar to the second check box "Match size with other pages".
Suggestion: please make "Auto Margins" a button, or even hide it into settings or additional dialog. Also, please clarify the logic of "Auto Margins" and its relations with "Original"  alignment.

**Comment by trufanov-nok** [comment]
This should be resolved now. As for details - they will be documented after I made a small changes in Origin alignment.
In a nutshell there is a scan (splitted and deskewed). You may use Page Detection with its settings to crop it by removing black borders around the scan. Then you may enable automargins and they'll be set equal to distance from content zone to scan borders (after age detection, if applied). So you end up with content box placed at it's "original" place with help of margins. But scans may differ in size due to cover page bigger then other pages, due to difference in split/deskew settings. Thus with "Match with others" enablet there still be gaps between content zone with automargins and final page size (which is equal to max page size). These gaps could be distributed proportionally with Original alignment to preserve "original" place of content zone. By proportional I mean distance from content box to scan size (after page detection if applied). So technically it's proportional to automargins, but not depend on it and could be applied to page layouts with no margins at all.
